version: '3.8'

services:
  api:
    build: ./rag-memo-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=tinyrag
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./rag-memo-api:/app
    networks:
      - tinyrag-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tinyrag-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tinyrag-network

volumes:
  mongodb_data:
  redis_data:

networks:
  tinyrag-network:
    driver: bridge 